### ISSUE TITLE
Impossible to get the entry id using the transformEntries function

### ISSUE THREAD

**Issue by PierreCavalet** [contentful/contentful-migration#1029]
## Expected Behavior
Being able to use `sys.id` and other info in the function used by `transformEntries`. 

For example:

```js
const myIdsToChange = ['a', 'b', 'c']

migration.transformEntries({
  contentType: 'newsArticle',
  from: ['sys.id'],
  to: ['myField'],
  transformEntryForLocale: function (fromFields, currentLocale) {
      if (currentLocale !== 'en-US') {
        return;
      }

      if (myIdsToChange.includes(fromFields.sys.id)) {
        return { myField: true };
      }
  }
});
```

Now I am aware "fromFields" variable name would be misleading. Maybe we could change it ?

## Actual Behavior
Currently it is not possible, we can only specify `fields` info, but not `sys` info. 

## Possible Solution

There are multiple solution to the problem. We could add a "fromSys" variable, we could always inject the entry ID, or we could allow the "pick" system to pick in the `sys` info even if it is not a field. 

Personally I would go towards the last one as it is very simple to implement, since we have all the information and we would just need to change the object in which lodash picks the properties:

https://github.com/contentful/contentful-migration/blob/168c7f2c02aab2caa3ac595c2dd136e2ed7609a0/src/lib/action/entry-transform.ts

replacing
```js
const inputs = _.pick(entry.fields, this.fromFields)

```
by
```js
const inputs = _.pick({id: entry.id, ...entry.fields}, this.fromFields)
```

would for example allow us to pick `id` and to use it in the `fromFields`.

I am open to suggestion and happy to contribute with a PR.

**Comment by AlanZambrano-at** [comment]
Me and my team would definitely benefit from this feature!

@PierreCavalet your suggestion sounds just fine!

**Comment by PierreCavalet** [comment]
A merge request is opened

**Comment by PierreCavalet** [comment]
any news on that one ? @ruderngespra

**Comment by PierreCavalet** [comment]
it's been 3 months, is anyone here ?

**Comment by jameyel** [comment]
+1. I need this for all of the transform functions.

**Comment by Crizzooo** [comment]
+1 we need this too

Can't we just pass `entry.sys` as the third argument to `transformEntryForLocale`?

We dont even need to allow users to pick from sys, sys will always be useful

**Comment by ruderngespra** [comment]
Very sorry for the delay! We discussed this internally and while we think this addition makes sense, we can not yet give a clear timeline as to when this will be implemented. I will keep you updated.

**Comment by EugeneEmelyanov** [comment]
+1. Need this as well, we have to write our own migration scripts manually to get access to entry.sys without `contentful-migration` to bypass this limitations

**Comment by dslovinsky** [comment]
+1 as well. Not having this is a pretty big limitation.
I prefer @Crizzooo's suggestion of having `entry.sys` be a third argument on `transformEntryForLocale`, since that would allow access for other data besides just `id`. I also don't think it makes sense for it to be combined with `fromFields` as it is in the open PR, since that would break the pattern of `fromField` properties being objects containing localized content.

IMO sys should also be available as an argument in the `identityKey` function. When using `transformEntriesToType` for example it makes sense to create the new entries with IDs that are a modification of the source entry ID (ex. a hash, or even just with a marker string appended) that way there is a clear, unique connection from the source entry to the generated one.

**Comment by marcolink** [comment]
This has been implemented: https://github.com/contentful/contentful-migration/releases/tag/v4.13.0
