### ISSUE TITLE
Allow multiple validation types in a single validation array

### ISSUE THREAD

**Issue by bradleither** [contentful/contentful-migration#188]
## Expected Behavior

When writing a script to enable validations on a RichText field, being able to use both `enabledMarks` and `enabledNodeTypes` on a single field should enable only the chosen nodes/marks.

example:
```
faqEntry.editField('answer', {
    validations: [
      {
        "enabledMarks": [
          "bold"
        ],
        "enabledNodeTypes": [
          "hyperlink"
        ]
      }
    ]
  });
```

## Actual Behavior

When trying to make changes to 2 different validation entries just the last one gets seen and all other entries get enabled.

## Possible Solution

Allow for multiple entries within the validations array.

**Comment by TimBeyer** [comment]
This is actually a somewhat unintuitive behavior of our API.
The list of validations needs to be a list of validation objects, with only a single key allowed for each.

So the correct approach would be

```js
faqEntry.editField('answer', {
  validations: [
    {
      "enabledMarks": [
        "bold"
      ]
    }, {
      "enabledNodeTypes": [
        "hyperlink"
      ]
    }
  ]
});
```

I'll close this ticket, but will consider adding improved types and validations in order to surface that behavior better.
