### ISSUE TITLE
Automatically generate migration

### ISSUE THREAD

**Issue by hrnik** [contentful/contentful-migration#30]
Hello, if I have existing space (with some data), can I automatically generate migration for the first time?

**Comment by hlabas** [comment]
Hi,

This is not available right now, but the following gist is the closest thing we tried out to experiment with:
https://gist.github.com/TimBeyer/89238eeadb358d1641cfedcaf670a8c8
With some adaptations (especially using the [CMA SDK](https://www.npmjs.com/package/contentful-management) to fetch the content types instead of getting them from a static file, this could be a start.
Other than that we don't yet have immediate plans to tackle this.

Thanks,
Hervé

**Comment by Khaledgarbaya** [comment]
you can do this using the [contentful-cli](https://github.com/contentful/contentful-cli), for more info check the [docs](https://github.com/contentful/contentful-cli/tree/master/docs/space/generate/migration)
