### ISSUE TITLE
Validation error using deriveLinkedEntries() with derivedContentType created in a previous migration.

### ISSUE THREAD

**Issue by dtrenz** [contentful/contentful-migration#512]
I am trying use `deriveLinkedEntries` to migrate entries from one content type to a new content type that was created in a previous migration.

## Expected Behavior
Migration validation passes, because the `derivedContentType` will be created in a previous migration.

## Actual Behavior
The following error is thrown during validation:
```
You cannot derive entries for content type "pet" because it has not yet been created.
```

## Possible Solution
The issue seems to be cause by this block of code:
https://github.com/contentful/contentful-migration/blob/master/src/lib/migration-chunks/validation/content-type.ts#L53-L60

I'm wondering if this should actually check for `!exists && !willBeCreated` instead of `!exists && willBeCreated`.

If so, these lines may also need to be updated:
https://github.com/contentful/contentful-migration/blob/master/src/lib/migration-chunks/validation/content-type.ts#L65-L67

## Steps to Reproduce
1. Create a migration that adds a new content type (e.g. `01-add-pet-content-type.js`).
2. Create a migration that uses `deriveLinkedEntries` to transform a field on a pre-existing source content type to a new field on the same source content type, with a `derivedContentType` set to the new content type that is added in the previous migration (e.g. `derivedContentType: 'pet'`).
4. Finally, run both migrations [using the library](https://github.com/contentful/contentful-migration#usage-as-a-library).

## Context

Pseudo-code example of desired outcome of a `deriveLinkedEntries` transformation migration...

### Before
```js
{
  dogs: [
    "rex",
    "spot"
  ]
}
```

### After
```js
{
  pets: [
    { name: "rex", type: "dog"},
    { name: "spot", type: "dog"}
  ]
}
```

## Environment

-   **Node Version**: 11.10.1
-   **Package Manager Version**: 6.7.0
-   **Operating System**: macOS 10.15.6 (Catalina)
-   **Package Version**: 1.6.2

**Comment by TimBeyer** [comment]
The line `!exists && willBeCreated` should be correct because we're checking whether in the same migration you have the ordering wrong. So if you were to derive something and create the target CT afterwards, it should warn you that while the migration file does include the CT to be created, at the time you want to use it, it has not yet been created.

Could you share the code that runs the two migrations using the library and maybe an example for the two migrations as well?
I am wondering if this is a problem with some accidentally shared state between two different uses of the library that leads to this.
