### ISSUE TITLE
Support for Compose `relationshipType` validation

### ISSUE THREAD

**Issue by kruczek-ynd** [contentful/contentful-migration#748]
## Expected Behavior

Migration allows setting of the `relationshipType` validation used in Compose as outlined in the [documentation](https://www.contentful.com/developers/docs/compose/cli-tools/)

## Actual Behavior

When running the migration the following error occurs:
```
Error: A field can't have "relationshipType" as a validation.
```

## Possible Solution

Modify `src/lib/offline-api/validator/schema/field-validations-schema.ts` to allow `relationshipType` as a validation, possibly adding it to `IValidation` as well.

## Steps to Reproduce

```js
export = function (migration) {
  const yourThing = migration.editContentType('your_thing')
  yourThing.editField('some_field').validations([{ relationshipType: ['Composition'] }]]
} as MigrationFunction
```

## Context

I wanted to migrate my setup to Compose and was unable to add this validation. Modifying the files on a built `contentful-migration` as outlined above allowed me to do so.

**Comment by makinwab** [comment]
Hi @kruczek-ynd,

The relationship type validation is supported in the experimental version of the tool. As is indicated in the [documentation](https://www.contentful.com/developers/docs/compose/cli-tools/) for the CLI, the same applies here.
Here's [the PR](https://github.com/contentful/contentful-migration/pull/701) with the relevant change.

Will close out this comment, feel free to re-open if you don't think the issue is addressed.
